BibCnrs/BibAdmin

docker-compose.base.yml
docker-compose.dev.yml
docker-compose.yml
js/login.js
js/main.js
public/login.html
webpack.config.js

[RFR] fix for IE

---

js/config/adminUsers.js
js/config/domains.js
js/config/inistAccounts.js
js/config/institutes.js
js/config/janusAccounts.js
js/config/menu.js
js/config/renaterHeaders.js
js/config/units.js
js/login.js
js/main.js
package.json

better names for terms, remove useless column, activate batch delete, add delete in list

[RFR] better ui

---

README.md

Il manque a mon avis des choses mais j'en ai profité pour initié un README

WIP -> try to have a first README (developemetn section)

---

js/config/janusAccounts.js

[Trello card](https://trello.com/c/AmGrASYr/1-0-25-bibadmin-la-saisie-d-un-commentaire-dans-la-zone-comment-d-un-compte-janus-n-est-pas-enregistree-apres-avoir-clique-sur-le-)

[RFR] Comments are not saved on Janus Account

---

js/main.js

[Trello card](https://trello.com/c/AmGrASYr/1-0-25-bibadmin-la-saisie-d-un-commentaire-dans-la-zone-comment-d-un-compte-janus-n-est-pas-enregistree-apres-avoir-clique-sur-le-) (see comment)

[RFR] Fix IE ajax cache

---

js/config/units.js

[Trello card](https://trello.com/c/hGH6CHRy/20-0-25-bibadmin-allonger-la-taille-de-la-zone-commentaire-dans-la-rubrique-unites-meme-taille-que-dans-la-zone-comment-de-la-rubri)

[RFR] Unit comments size

---

package.json

[Trello card](https://trello.com/c/KiSMQpMd)
Fixed by https://github.com/marmelab/ng-admin/pull/1290

[RFR] Upgrade ng-admin to fix filter submition

---

js/main.js

[Trello card](https://trello.com/c/JU2bodC7)

[RFR] Fix export of large datasets by settings the request timeout to a large value too

---

js/config/database.js
js/config/menu.js
js/directives/bibImage.js
js/directives/index.js
js/main.js
js/services/index.js
js/services/readImageAsDataUrl.js
package.json

waiting for production deployment

[RFR] Database admin

---

js/config/units.js

[Trello card](https://trello.com/c/wyTxe746)

[RFR] Make accounts numbers links to accounts list with filters

---

js/config/janusAccounts.js
js/directives/bibExportToCsv.js
js/directives/index.js
js/main.js
package.json

[Trello card](https://trello.com/c/pe4lRCPa)

[RFR] Faster Janus Accounts export

---

js/directives/bibExportToCsv.js

[Trello card](https://trello.com/c/pe4lRCPa)

[RFR] Fix janus account export

---

js/directives/bibExportToCsv.js
public/index.css
public/index.html

[RFR] Add spinner to export button

---

js/config/units.js

linked to https://github.com/BibCnrs/BibApi/pull/158

[RFR] remove nb_unit_account from unit creation form to avoid null value

---

js/config/janusAccounts.js

linked to https://github.com/BibCnrs/BibApi/pull/162

[RFR] add fist_connexion field in janus_account admin

---

js/login.js
public/index.html

https://trello.com/c/4tnPzI9J/35-1-bibadmin-d%C3%A9tecter-les-identifiants-utilisateur-identiques-et-mettre-en-place-un-syst%C3%A8me-dalerte-par-messagerie-%C3%A9lectronique
Allow to access janusAccount page from link.

[RFR] remember link on login

---

js/config/communities.js
js/config/database.js
js/config/inistAccounts.js
js/config/janusAccounts.js
js/config/units.js

https://trello.com/c/PNDfWAve/148-025bibadmin-remplacer-boolean-field-to-use-a-checkbox

[RFR] mark boolean field as required to display a checkbox

---

js/config/menu.js
js/config/revue.js
js/main.js

https://trello.com/c/xXn8RRZg/106-2-option-3-bibcnrs-initialisation-des-ressources-favorites-pour-lutilisateur

[RFR] add admin for revue

---

package-lock.json
package.json
src/App.js
src/components/Databases.js
src/components/Inist.js
src/components/Janus.js
src/components/Units.js
src/i18n/fr.js
src/index.css

- complete relation between page
- update dependencies

add list for "Base de données"

---

src/App.js
src/components/Inist.js
src/components/Janus.js
src/components/Units.js
src/i18n/fr.js

Add edit and create for page "inist" and "unités", add fields for janus.

Add edit and create for page "inist" and "unités", add fields for janus.

---

src/App.js
src/components/Communities.js
src/components/Databases.js
src/components/Inist.js
src/components/Instituts.js
src/components/Janus.js
src/components/Sections.js
src/i18n/fr.js

fix multiple bug with previous version

add create and edit for communities and section

---

src/App.js
src/components/Communities.js
src/components/Dashboard.js
src/components/Databases.js
src/components/Inist.js
src/components/Instituts.js
src/components/Janus.js
src/components/Sections.js
src/components/Units.js
src/components/Users.js
src/i18n/fr.js

- add redirect
- add missing fields
- fix other bug

add dashboard and fix multiple bug

---

src/App.js
src/components/Communities.js
src/components/Databases.js
src/components/Favoris.js
src/components/Inist.js
src/components/Instituts.js
src/components/Janus.js
src/components/Sections.js
src/components/Units.js
src/components/Users.js
src/i18n/fr.js
src/index.css
src/utils/jsonServerProvider.js

- improve the interface
- add sort for some fields
- increase the size of input in form
- fix other bugs

add page "ressources favorites"

---

src/components/Inist.js
src/index.css

Added password generator for INIST accounts. The password is random and has a length of 6 characters.

add PasswordGenerator

---

src/components/Communities.js
src/components/Databases.js
src/components/Favoris.js
src/components/Inist.js
src/components/Instituts.js
src/components/Janus.js
src/components/Sections.js
src/components/Units.js
src/components/Users.js

- add generatePassword for edit INIST

fix bug redirect after submit

---

src/components/Inist.js
src/components/Instituts.js
src/components/Janus.js
src/components/Units.js
src/i18n/fr.js
src/index.css

The filters should now be functional everywhere.

fix bug filter with INIST, JANUS, institus and Unités

---

src/components/Communities.js
src/components/Databases.js
src/components/Favoris.js
src/components/Inist.js
src/components/Instituts.js
src/components/Janus.js
src/components/Sections.js
src/components/Units.js
src/index.css
src/utils/jsonServerProvider.js

fix bug bad display for filter
- sort by default alphabetical order

add link for edit content :tada:

---

package-lock.json
package.json
public/index.html
src/views/Inist.js
src/views/Janus.js

fix bug with filter which don't work with date

---

package-lock.json
package.json
src/index.css

- add scrollbar vertical with autocomplete

update react-admin with version 2.3.4

---

package-lock.json
package.json
src/components/LinkEdit.js
src/index.css
src/views/Units.js

- fix duplicare field in edit and create unit

fix bug bad link

---

.eslintrc
docker-compose.yml
package-lock.json
package.json
src/App.js
src/components/AutoCompleteInput.js
src/components/DeleteButtonWithConfirmation.js
src/components/FrenchDateInput.js
src/components/ListActions.js
src/i18n/fr.js
src/index.css
src/index.js
src/registerServiceWorker.js
src/utils/jsonServerProvider.js
src/views/Dashboard.js
src/views/Databases.js
src/views/Inist.js
src/views/Instituts.js
src/views/Janus.js
src/views/Sections.js
src/views/Units.js
src/views/Users.js

upgrade react-admin to 3.3.0 and update all dependencies

---

package-lock.json
package.json
src/dataProvider.ts
src/licenses/LicenseCreate.tsx
src/licenses/LicenseEdit.tsx

Feat: Update PDF upload for license

---

src/dataProvider.ts
src/licenses/LicenseCreate.tsx
src/licenses/LicenseList.tsx

Feat: Add common license
